apiVersion: v1
kind: Service
metadata:
  name: thesis-ldap-clip
spec:
  type: ClusterIP
  selector:
    component: thesis-ldap
  ports:
    - port: 8080
      targetPort: 3000
      name: thesis-ldap
      protocol: TCP
